/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import FiltersAndOthers.AddPropertyListToCadArea;
import TableModels.ZoznamNehnutelnostiPreKatTabModel;
import TableModels.ZoznamNehnutelnostiTabModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import mainpackage.Logika;
import javax.swing.SwingConstants;
import mainpackage.CadastralArea;
import mainpackage.Globals;
import mainpackage.MainSystem;

/**
 *
 * @author Vladko
 */
public class KatastralneUzemie extends javax.swing.JPanel {

    Logika logika = new Logika();
    JFrame mainWindow = new JFrame();
    MainSystem system = new MainSystem();
    CadastralArea cadastralAreaBeforeChanges;

    public KatastralneUzemie(JFrame frame, MainSystem system) {
        initComponents();
        this.mainWindow = frame;
        this.system = system;
        InicializationNew();

    }

    public KatastralneUzemie(JFrame frame, MainSystem system, int index) {
        initComponents();
        this.system = system;
        this.mainWindow = frame;
        if (index == 0) {
            InicializationNew();
        } else {
            Inicialization();
        }
    }

    public KatastralneUzemie(JFrame frame, MainSystem system, CadastralArea area) {
        initComponents();
        this.mainWindow = frame;
        this.system = system;
        Inicialization(area);
        cadastralAreaBeforeChanges = area;
    }

    private void Inicialization(CadastralArea area) {
        jPanel1.add(jLabel2, SwingConstants.CENTER);
        numberCadAreaTF.setEditable(false);
        titleCadAreaTF.setEditable(false);
        addBT.setEnabled(false);
        saveBT.setEnabled(false);

        numberCadAreaTF.setText(Integer.toString(area.getNumbCadArea()));
        titleCadAreaTF.setText(area.getTitleCadArea());
        showList();
    }

    private void Inicialization() {
        jPanel1.add(jLabel2, SwingConstants.CENTER);
        numberCadAreaTF.setEditable(false);
        titleCadAreaTF.setEditable(false);
        addBT.setEnabled(false);
        saveBT.setEnabled(false);

    }

    private void InicializationNew() {
        jPanel1.add(jLabel2, SwingConstants.CENTER);
        numberCadAreaTF.setEditable(true);
        titleCadAreaTF.setEditable(true);
        addBT.setEnabled(true);
        saveBT.setEnabled(false);
        editBT.setEnabled(false);

    }

    public void showList() {

        jTable1.setModel(new ZoznamNehnutelnostiPreKatTabModel(system.findCadAreaByNumber(Integer.parseInt(numberCadAreaTF.getText())).getPropertiesOnCadArea()));
        jTable2.setModel(new TableModels.ZoznamListovVlastnictvaTabModel1(system.findCadArea(Integer.parseInt(numberCadAreaTF.getText())).getPropertyListsOnArea()));
        //ZoznamNehnutelnostiTabModel model = new ZoznamNehnutelnostiTabModel(system.getProperties());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numberCadAreaTF = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titleCadAreaTF = new javax.swing.JTextField();
        saveBT = new javax.swing.JButton();
        addBT = new javax.swing.JButton();
        addPropertyListBT = new javax.swing.JButton();
        editBT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("Číslo katastrálneho územia:");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setLabelFor(jLabel1);
        jLabel2.setText("Katastrálne územie");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setText("Názov katastrálneho územia:");

        saveBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        saveBT.setText("Ulož zmeny");
        saveBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTActionPerformed(evt);
            }
        });

        addBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.png"))); // NOI18N
        addBT.setText("Pridaj územie");
        addBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTActionPerformed(evt);
            }
        });

        addPropertyListBT.setText("Pridanie listu vlastníctva");
        addPropertyListBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPropertyListBTActionPerformed(evt);
            }
        });

        editBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        editBT.setText("Uprav územie");
        editBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel4.setText("Zoznam nehnuteľností");

        jLabel5.setText("Zoznam vlastníckych listov");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberCadAreaTF)
                            .addComponent(titleCadAreaTF, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addPropertyListBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveBT))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(443, 443, 443))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberCadAreaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(titleCadAreaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBT)
                    .addComponent(saveBT)
                    .addComponent(addPropertyListBT)
                    .addComponent(editBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTActionPerformed
        if (numberCadAreaTF.getText().isEmpty() || titleCadAreaTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(mainWindow, "Vyplňte meno, priezvisko, rodné číslo.");
            return;
        } else {
            system.addCadArea(Integer.parseInt(numberCadAreaTF.getText()), titleCadAreaTF.getText());
            numberCadAreaTF.setText("");
            titleCadAreaTF.setText("");
        }
    }//GEN-LAST:event_addBTActionPerformed

    private void editBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTActionPerformed
        numberCadAreaTF.setEditable(true);
        titleCadAreaTF.setEditable(true);

        saveBT.setEnabled(true);
    }//GEN-LAST:event_editBTActionPerformed

    private void saveBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTActionPerformed
        if (numberCadAreaTF.getText().isEmpty() || titleCadAreaTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(mainWindow, "Číslo a názov katastálneho územia musia byť vyplnené.");
            return;
        } else {
            ((CadastralArea) system.getCadastralAreaLists().findNode(cadastralAreaBeforeChanges).getData()).setNumbCadArea(Integer.parseInt(numberCadAreaTF.getText()));
            ((CadastralArea) system.getCadastralAreaLists().findNode(cadastralAreaBeforeChanges).getData()).setTitleCadArea(titleCadAreaTF.getText());
        }
    }//GEN-LAST:event_saveBTActionPerformed

    private void addPropertyListBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPropertyListBTActionPerformed
        AddPropertyListToCadArea ca = new AddPropertyListToCadArea(system, numberCadAreaTF.getText(), this);
    }//GEN-LAST:event_addPropertyListBTActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {

            int selectedRowIndex = jTable1.getSelectedRow();

            String regNumb = jTable1.getValueAt(selectedRowIndex, 0).toString();
            String adress = jTable1.getValueAt(selectedRowIndex, 1).toString();
            String desc = jTable1.getValueAt(selectedRowIndex, 2).toString();

            Nehnutelnost panel = new Nehnutelnost(mainWindow, system, system.findPropertyByRegNumb(Integer.parseInt(regNumb)));
            Globals.panel.addTab("Nehnuteľnosť " + regNumb, panel);
            logika.setLastTab();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        if (evt.getClickCount() == 2) {

            int selectedRowIndex = jTable2.getSelectedRow();
            String numberPropertyList = jTable2.getValueAt(selectedRowIndex, 0).toString();

            ListVlastnictva panel = new ListVlastnictva(mainWindow, system, system.findPropertyListByNumber(Integer.parseInt(numberPropertyList)));
            Globals.panel.addTab("List vlastníctva " + numberPropertyList, panel);
            logika.setLastTab();
        }
    }//GEN-LAST:event_jTable2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBT;
    private javax.swing.JButton addPropertyListBT;
    private javax.swing.JButton editBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField numberCadAreaTF;
    private javax.swing.JButton saveBT;
    private javax.swing.JTextField titleCadAreaTF;
    // End of variables declaration//GEN-END:variables
}
