/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import FiltersAndOthers.ChangeCadAreaOnList;
import FiltersAndOthers.ChangeOwnersParts;
import TableModels.ZoznamNehnutelnostiTabModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import mainpackage.Logika;
import javax.swing.SwingConstants;
import mainpackage.CadastralArea;
import mainpackage.Globals;
import mainpackage.MainSystem;
import mainpackage.Property;
import mainpackage.PropertyList;

/**
 *
 * @author Vladko
 */
public class ListVlastnictva extends javax.swing.JPanel {

    Logika logika = new Logika();
    JFrame mainWindow = new JFrame();
    MainSystem system;

    public ListVlastnictva(JFrame frame, MainSystem system) {
        initComponents();
        mainWindow = frame;
        this.system = system;

        InicializationNew();

    }

    public ListVlastnictva(JFrame frame, MainSystem system, int index) {
        this.mainWindow = frame;
        this.system = system;
        initComponents();
        if (index == 0) {
            InicializationNew();
        } else {
            Inicialization();
        }
    }

    public ListVlastnictva(JFrame frame, MainSystem system, PropertyList list) {
        initComponents();
        this.mainWindow = frame;
        this.system = system;
        Inicialization(list);
    }

    private void Inicialization(PropertyList list) {
        jPanel1.add(jLabel2, SwingConstants.CENTER);
        numbPropertListTF.setEditable(false);
        numberCadAreaTF.setEditable(false);
        titleCadAreaTF.setEditable(false);
        addBT.setEnabled(false);
        saveBT.setEnabled(false);
        editBT.setEnabled(true);

        if (list.getCadastralArea() != null) {
            numberCadAreaTF.setText(Integer.toString(list.getCadastralArea().getNumbCadArea()));
            titleCadAreaTF.setText(list.getCadastralArea().getTitleCadArea());
        } else {
            numberCadAreaTF.setText("");
            titleCadAreaTF.setText("");
        }
        numbPropertListTF.setText(Integer.toString(list.getNumbProperList()));
        showList();
    }

    private void Inicialization() {
        jPanel1.add(jLabel2, SwingConstants.CENTER);
        numberCadAreaTF.setEditable(false);
        numbPropertListTF.setEditable(false);
        addBT.setEnabled(false);
        saveBT.setEnabled(true);
    }

    private void InicializationNew() {
        jPanel1.add(jLabel2, SwingConstants.CENTER);
        numberCadAreaTF.setEditable(true);
        numbPropertListTF.setEditable(true);
        addBT.setEnabled(true);
        saveBT.setEnabled(false);
        editBT.setEnabled(false);
        titleCadAreaTF.setEnabled(false);
    }

    public void showList() {
        jTable4.setModel(new ZoznamNehnutelnostiTabModel(system.findPropertyListByNumber(Integer.parseInt(numbPropertListTF.getText())).getPropertiesOnList()));
        jTable3.setModel(new TableModels.ZoznamPodielovNaListeVlastnictva(system.findPropertyListByNumber(Integer.parseInt(numbPropertListTF.getText())).getOwnership().getPersons(), system.findPropertyListByNumber(Integer.parseInt(numbPropertListTF.getText())).getOwnership().getPersonParts()));
        if (system.findPropertyListByNumber(Integer.parseInt(numbPropertListTF.getText())).getCadastralArea() != null) {
            numberCadAreaTF.setText(Integer.toString(system.findPropertyListByNumber(Integer.parseInt(numbPropertListTF.getText())).getCadastralArea().getNumbCadArea()));
            titleCadAreaTF.setText(system.findPropertyListByNumber(Integer.parseInt(numbPropertListTF.getText())).getCadastralArea().getTitleCadArea());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numberCadAreaTF = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numbPropertListTF = new javax.swing.JTextField();
        saveBT = new javax.swing.JButton();
        addBT = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        addPropertyBT = new javax.swing.JButton();
        deleteOwnershipInterestBT = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        editBT = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        titleCadAreaTF = new javax.swing.JTextField();
        addPropertyTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        changeCadBT = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        regNumbOfOwnerTF = new javax.swing.JTextField();
        addOwner = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Číslo katastrálneho územie:");

        numberCadAreaTF.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setLabelFor(jLabel1);
        jLabel2.setText("List vlastníctva");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setText("Číslo listu vlastníctva:");

        saveBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        saveBT.setText("Ulož zmeny");

        addBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.png"))); // NOI18N
        addBT.setText("Pridaj list vlastníctva");
        addBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel6.setText("Nehnuteľnosti na liste vlastníctva");

        jLabel7.setText("Vlastníci nehnuteľností");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        addPropertyBT.setText("Pridaj nehnuteľnosť");
        addPropertyBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPropertyBTActionPerformed(evt);
            }
        });

        deleteOwnershipInterestBT.setText("Odstránenie majetkového podieľu");
        deleteOwnershipInterestBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOwnershipInterestBTActionPerformed(evt);
            }
        });

        jButton1.setText("Zmena majetkového podielu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        editBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        editBT.setText("Uprav list");
        editBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTActionPerformed(evt);
            }
        });

        jLabel4.setText("Názov katastrálneho úzamia:");

        titleCadAreaTF.setEnabled(false);

        addPropertyTF.setToolTipText("Súpisné číslo");

        jLabel5.setText("Súpisné číslo nehnuteľnosti:");

        changeCadBT.setText("Zmeň katastrálne územie");
        changeCadBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeCadBTActionPerformed(evt);
            }
        });

        jLabel8.setText("Rodné číslo:");

        addOwner.setText("Pridať majiteľa");
        addOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOwnerActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButton2.setText("Odstráň nehnuteľnosť");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(changeCadBT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addBT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editBT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveBT))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numbPropertListTF)
                                    .addComponent(numberCadAreaTF)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleCadAreaTF))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addPropertyTF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addPropertyBT))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(regNumbOfOwnerTF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addOwner))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteOwnershipInterestBT)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numbPropertListTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numberCadAreaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(titleCadAreaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBT)
                    .addComponent(editBT)
                    .addComponent(saveBT)
                    .addComponent(changeCadBT))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addPropertyBT)
                            .addComponent(addPropertyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(regNumbOfOwnerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addOwner))))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteOwnershipInterestBT)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTActionPerformed
        if (numbPropertListTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(mainWindow, "Vyplňte číslo listu vlastníctva");
            return;
        } else if (!numberCadAreaTF.getText().isEmpty()) {
            if (system.findCadArea(Integer.parseInt(numberCadAreaTF.getText())) != null) { //tieto podmienky zrusit vsak lebo do stromu ked vlkadam tak vrati null
                system.addPropertyList(system.findCadArea(Integer.parseInt(numberCadAreaTF.getText())), Integer.parseInt(numbPropertListTF.getText()));
                system.findCadArea(Integer.parseInt(numberCadAreaTF.getText())).addPropertyList(system.findPropertyListByNumber(Integer.parseInt(numbPropertListTF.getText())));
                numbPropertListTF.setText("");
                numberCadAreaTF.setText("");
                JOptionPane.showMessageDialog(mainWindow, "List vlastníctva bol úspešne vytvorený.");

            } else {
                JOptionPane.showMessageDialog(mainWindow, "Katastrálne územie s daným číslom neexistuje.");
                return;
            }

        } else {
            system.addPropertyList(new PropertyList(Integer.parseInt(numbPropertListTF.getText())));
            numbPropertListTF.setText("");
            JOptionPane.showMessageDialog(mainWindow, "List vlastníctva bol úspešne vytvorený.");
        }
    }//GEN-LAST:event_addBTActionPerformed

    private void editBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTActionPerformed
        saveBT.setEnabled(true);
        numbPropertListTF.setEditable(true);
        numberCadAreaTF.setEditable(true);
        titleCadAreaTF.setEditable(true);
    }//GEN-LAST:event_editBTActionPerformed

    private void addPropertyBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPropertyBTActionPerformed
        if (system.findPropertyByRegNumb(Integer.parseInt(addPropertyTF.getText())).getPropertyList() == null) {
            //system.findPropertyByRegNumb(Integer.parseInt(addPropertyTF.getText())).setList(system.findPropertyListByNumber(Integer.parseInt(numbPropertListTF.getText())));
            //system.findCadAreaByNumber(numberCadAreaTF.getText()).addProperty(system.findPropertyByRegNumb(addPropertyTF.getText()));
            // system.findPropertyByRegNumb(Integer.parseInt(addPropertyTF.getText())).setCadArea(system.findCadAreaByNumber(Integer.parseInt(numberCadAreaTF.getText())));
            //system.findPropertyListByNumber(Integer.parseInt(numbPropertListTF.getText())).addPropertyOnList(system.findPropertyByRegNumb(Integer.parseInt(addPropertyTF.getText())));
            //system.findCadArea(Integer.parseInt(numberCadAreaTF.getText())).addProperty(system.findPropertyByRegNumb(Integer.parseInt(addPropertyTF.getText())));
            system.addPropertyOnPropertyList(Integer.parseInt(numbPropertListTF.getText()), Integer.parseInt(addPropertyTF.getText()), Integer.parseInt(numberCadAreaTF.getText()));
            addPropertyTF.setText("");
            showList();
        } else {
            JOptionPane.showMessageDialog(mainWindow, "Nehnutelnosť je už zapísaná na dákom liste vlastníctva.");
            return;
        }
    }//GEN-LAST:event_addPropertyBTActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        if (evt.getClickCount() == 2) {

            int selectedRowIndex = jTable4.getSelectedRow();

            String regNumb = jTable4.getValueAt(selectedRowIndex, 0).toString();
            String adress = jTable4.getValueAt(selectedRowIndex, 1).toString();
            String desc = jTable4.getValueAt(selectedRowIndex, 2).toString();

            Nehnutelnost panel = new Nehnutelnost(mainWindow, system, system.findPropertyByRegNumb(Integer.parseInt(regNumb)));
            Globals.panel.addTab("Nehnuteľnosť " + regNumb, panel);
            logika.setLastTab();
        }
    }//GEN-LAST:event_jTable4MouseClicked

    private void changeCadBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeCadBTActionPerformed
        ChangeCadAreaOnList ch = new ChangeCadAreaOnList(system, Integer.parseInt(numbPropertListTF.getText()), this);
    }//GEN-LAST:event_changeCadBTActionPerformed

    private void addOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOwnerActionPerformed
        system.addOwnerToPropertyList(Integer.parseInt(numbPropertListTF.getText()), Long.parseLong(regNumbOfOwnerTF.getText()));
        //system.findPropertyListByNumber(Integer.parseInt(numbPropertListTF.getText())).getOwnership().addPerson(system.findPersonByID(Long.parseLong(regNumbOfOwnerTF.getText())));
        //system.findPersonByID(Long.parseLong(regNumbOfOwnerTF.getText())).addPropertyList(system.findPropertyListByNumber(Integer.parseInt(numbPropertListTF.getText())));
        ChangeOwnersParts ow = new ChangeOwnersParts(this, system, system.findPropertyListByNumber(Integer.parseInt(numbPropertListTF.getText())).getOwnership().getPersonParts(), numbPropertListTF.getText());
        showList();
        regNumbOfOwnerTF.setText("");
    }//GEN-LAST:event_addOwnerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ChangeOwnersParts pa = new ChangeOwnersParts(this, system, system.findPropertyListByNumber(Integer.parseInt(numbPropertListTF.getText())).getOwnership().getPersonParts(), numbPropertListTF.getText());
        /*
        if(jTable3.getSelectedRow()>= 0){
            system.findPropertyListByNumber(numbPropertListTF.getText()).getOwnership().changeParts(jTable3.getValueAt(jTable3.getSelectedRow(), 2).toString(), Double.parseDouble(partOfOwnerTF.getText()));
            showList();
        }else{
            JOptionPane.showMessageDialog(mainWindow, "Zvoľte majiteľa, ktorému chcete zmeniť majtekový podiel.");  
        }
         */
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteOwnershipInterestBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOwnershipInterestBTActionPerformed
        int row = jTable3.getSelectedRow();
        if (row >= 0) {
            String identifNumb = jTable3.getModel().getValueAt(row, 2).toString();
            if (system.findPropertyListByNumber(Integer.parseInt(numbPropertListTF.getText())).deleteOwners(Integer.parseInt(identifNumb))) {
                system.findPersonByID(Long.parseLong(identifNumb)).deletePropertyList(Integer.parseInt(numbPropertListTF.getText()));
                showList();
                ChangeOwnersParts ch = new ChangeOwnersParts(this, system, system.findPropertyListByNumber(Integer.parseInt(numbPropertListTF.getText())).getOwnership().getPersonParts(), numbPropertListTF.getText());
            } else {
                JOptionPane.showMessageDialog(mainWindow, "Zvolte majiteľa");
                return;
            }
        }
    }//GEN-LAST:event_deleteOwnershipInterestBTActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        if (evt.getClickCount() == 2) {

            int selectedRowIndex = jTable3.getSelectedRow();

            String firstName = jTable3.getValueAt(selectedRowIndex, 0).toString();
            String surName = jTable3.getValueAt(selectedRowIndex, 1).toString();
            String identifNum = jTable3.getValueAt(selectedRowIndex, 2).toString();
            String permResidence = jTable3.getValueAt(selectedRowIndex, 3).toString();

            Obcan panel = new Obcan(mainWindow, system, system.findPersonByID(Long.parseLong(identifNum)));
            Globals.panel.addTab("Občan " + surName, panel);
            logika.setLastTab();
        }
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = jTable4.getSelectedRow();
        if (row >= 0) {
            String deleteProperty = jTable4.getModel().getValueAt(row, 0).toString();
            system.findPropertyListByNumber(Integer.parseInt(numbPropertListTF.getText())).getPropertiesOnList().delete(new Property(Integer.parseInt(deleteProperty), "", ""));
            system.findCadAreaByNumber(Integer.parseInt(numberCadAreaTF.getText())).deleteProperty(new Property(Integer.parseInt(deleteProperty), "", ""));
            system.findPropertyByRegNumb(Integer.parseInt(deleteProperty)).setCadArea(null);
            system.findPropertyByRegNumb(Integer.parseInt(deleteProperty)).setList(null);
            
        }
        showList();


    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBT;
    private javax.swing.JButton addOwner;
    private javax.swing.JButton addPropertyBT;
    private javax.swing.JTextField addPropertyTF;
    private javax.swing.JButton changeCadBT;
    private javax.swing.JButton deleteOwnershipInterestBT;
    private javax.swing.JButton editBT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField numbPropertListTF;
    private javax.swing.JTextField numberCadAreaTF;
    private javax.swing.JTextField regNumbOfOwnerTF;
    private javax.swing.JButton saveBT;
    private javax.swing.JTextField titleCadAreaTF;
    // End of variables declaration//GEN-END:variables
}
