/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JFrame;
import javax.swing.UIManager;
import mainpackage.Globals;
import mainpackage.Logika;
import mainpackage.MainSystem;

/**
 *
 * @author Vladko
 */
public class MainWindow extends javax.swing.JFrame {

    private MainSystem system;
    private Logika logika = new Logika();
    

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        system = new MainSystem();
        initComponents();
        inicialization();
  
        this.setExtendedState(this.getExtendedState() | MainWindow.MAXIMIZED_BOTH);
        //this.setExtendedState(this.getExtendedState() | mainpackage.MainWindow.MAXIMIZED_BOTH);

    }

    public void inicialization() {
        Globals.panel = panelWithTabs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        CitizienBT = new javax.swing.JButton();
        ListCitiziensBT = new javax.swing.JButton();
        ListCadAreaBT = new javax.swing.JButton();
        propertyListBT = new javax.swing.JButton();
        ListOfPropertyListsBT = new javax.swing.JButton();
        propertyBT = new javax.swing.JButton();
        listPropertyBT = new javax.swing.JButton();
        CadAreaBT = new javax.swing.JButton();
        panelWithTabs = new GUI.JTabbedPaneWithCloseIcons();
        CloseAll = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        generateBT = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CitizienBT.setText("Občan");
        CitizienBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitizienBTActionPerformed(evt);
            }
        });

        ListCitiziensBT.setText("Zoznam Občanov");
        ListCitiziensBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListCitiziensBTActionPerformed(evt);
            }
        });

        ListCadAreaBT.setText("Zoznam katastrálnych území");
        ListCadAreaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListCadAreaBTActionPerformed(evt);
            }
        });

        propertyListBT.setText("List vlastníctva");
        propertyListBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertyListBTActionPerformed(evt);
            }
        });

        ListOfPropertyListsBT.setText("Zoznam listov vlastníctva");
        ListOfPropertyListsBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListOfPropertyListsBTActionPerformed(evt);
            }
        });

        propertyBT.setText("Nehnuteľnosť");
        propertyBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertyBTActionPerformed(evt);
            }
        });

        listPropertyBT.setText("Zoznam nehnuteľností");
        listPropertyBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPropertyBTActionPerformed(evt);
            }
        });

        CadAreaBT.setText("Katastrálne územie");
        CadAreaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadAreaBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CadAreaBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CitizienBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ListCitiziensBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(propertyBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(listPropertyBT, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                            .addComponent(ListCadAreaBT, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ListOfPropertyListsBT, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(propertyListBT, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CitizienBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListCitiziensBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertyBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listPropertyBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CadAreaBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListCadAreaBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertyListBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListOfPropertyListsBT)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        panelWithTabs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CloseAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closeAll.jpg"))); // NOI18N
        CloseAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseAllActionPerformed(evt);
            }
        });

        jButton1.setText("Import");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        generateBT.setText("Generuj");
        generateBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBTActionPerformed(evt);
            }
        });

        jButton2.setText("Export");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CloseAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelWithTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CloseAll)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generateBT))
                    .addComponent(panelWithTabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseAllActionPerformed
        panelWithTabs.removeAll();
    }//GEN-LAST:event_CloseAllActionPerformed

    private void CitizienBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitizienBTActionPerformed
        Obcan panel = new Obcan(this, system, 0);
        panelWithTabs.addTab("Občan", panel);
        logika.setLastTab();
    }//GEN-LAST:event_CitizienBTActionPerformed

    private void ListCitiziensBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListCitiziensBTActionPerformed
        ZoznamObcanov panel = new ZoznamObcanov(this, system);
        panelWithTabs.addTab("Zoznam občanov", panel);
        logika.setLastTab();
    }//GEN-LAST:event_ListCitiziensBTActionPerformed

    private void CadAreaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadAreaBTActionPerformed
        KatastralneUzemie panel = new KatastralneUzemie(this, system, 0);
        panelWithTabs.addTab("Katastrálne územie", panel);
        logika.setLastTab();
    }//GEN-LAST:event_CadAreaBTActionPerformed

    private void propertyListBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertyListBTActionPerformed
        ListVlastnictva panel = new ListVlastnictva(this, system, 0);
        panelWithTabs.addTab("List vlastníctva", panel);
        logika.setLastTab();
    }//GEN-LAST:event_propertyListBTActionPerformed

    private void ListOfPropertyListsBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListOfPropertyListsBTActionPerformed
        ZoznamListovVlastnictva panel = new ZoznamListovVlastnictva(this, system);
        panelWithTabs.addTab("Zoznam listov vlastníctva", panel);
        logika.setLastTab();
    }//GEN-LAST:event_ListOfPropertyListsBTActionPerformed

    private void propertyBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertyBTActionPerformed
        Nehnutelnost panel = new Nehnutelnost(this, system, 0);
        panelWithTabs.addTab("Nehnuteľnosť", panel);
        logika.setLastTab();
    }//GEN-LAST:event_propertyBTActionPerformed

    private void listPropertyBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPropertyBTActionPerformed
        ZoznamNehnutelnosti panel = new ZoznamNehnutelnosti(this, system);
        panelWithTabs.addTab("Zoznam nehnuteľností", panel);
        logika.setLastTab();

    }//GEN-LAST:event_listPropertyBTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            system.nacitajData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ListCadAreaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListCadAreaBTActionPerformed
        ZoznamKatastralnychUzemi panel = new ZoznamKatastralnychUzemi(this, system);
        panelWithTabs.addTab("Zoznam katastrálnych území", panel);
        logika.setLastTab();
    }//GEN-LAST:event_ListCadAreaBTActionPerformed

    private void generateBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBTActionPerformed
        system.generateData();
    }//GEN-LAST:event_generateBTActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        system.exportData();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* //menenie dizajnu look and feel
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
        }
        */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadAreaBT;
    private javax.swing.JButton CitizienBT;
    private javax.swing.JButton CloseAll;
    private javax.swing.JButton ListCadAreaBT;
    private javax.swing.JButton ListCitiziensBT;
    private javax.swing.JButton ListOfPropertyListsBT;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JButton generateBT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton listPropertyBT;
    private GUI.JTabbedPaneWithCloseIcons panelWithTabs;
    private javax.swing.JButton propertyBT;
    private javax.swing.JButton propertyListBT;
    // End of variables declaration//GEN-END:variables
}
