/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import mainpackage.Logika;
import javax.swing.SwingConstants;
import mainpackage.CadastralArea;
import mainpackage.Globals;
import mainpackage.MainSystem;
import mainpackage.Person;
import mainpackage.Property;
import mainpackage.PropertyList;

/**
 *
 * @author Vladko
 */
public class Nehnutelnost extends javax.swing.JPanel {

    Logika logika = new Logika();
    JFrame mainWindow = new JFrame();
    MainSystem system = new MainSystem();
    Property propertyBeforeChanges = new Property();

    public Nehnutelnost(JFrame frame, MainSystem system, int index) {
        initComponents();
        mainWindow = frame;
        this.system = system;
        if (index == 0) {
            InicializationNew();
        } else {
            Inicialization();
        }

    }

    public Nehnutelnost(JFrame frame, MainSystem system, Property property) {
        initComponents();
        mainWindow = frame;
        this.system = system;

        propertyBeforeChanges = property;
        Inicialization(property);

    }

    private void Inicialization() {
        jPanel1.add(jLabel2, SwingConstants.CENTER);
        regNumbTF.setEditable(false);
        adressTF.setEditable(false);
        descriptionTF.setEditable(false);
        adddBT.setEnabled(false);
        saveBT.setEnabled(true);
        ownerIDTF.setEnabled(true);
        addOwnerBT.setEnabled(true);

    }

    private void InicializationNew() {
        jPanel1.add(jLabel2, SwingConstants.CENTER);
        regNumbTF.setEditable(true);
        adressTF.setEditable(true);
        descriptionTF.setEditable(true);
        adddBT.setEnabled(true);
        saveBT.setEnabled(false);
        editBT.setEnabled(false);
    }

    private void Inicialization(Property property) {
        jPanel1.add(jLabel2, SwingConstants.CENTER);
        regNumbTF.setEditable(false);
        adressTF.setEditable(false);
        descriptionTF.setEditable(false);
        adddBT.setEnabled(false);
        saveBT.setEnabled(false);

        regNumbTF.setText(Integer.toString(property.getRegNumber()));
        regNumbTF.getText();
        adressTF.setText(property.getAdress());
        descriptionTF.setText(property.getDescription());
        ownerIDTF.setEnabled(true);
        addOwnerBT.setEnabled(true);
        addCitizienTF.setEnabled(true);
        addCitizienBT.setEnabled(true);
        partTF.setEnabled(true);

        if (property.getCadArea() != null) {
            numbOfCatAreaTF.setText(Integer.toString(property.getCadArea().getNumbCadArea()));
        }

        if (property.getPropertyList() != null) {
            propertyListTF.setText(Integer.toString(property.getPropertyList().getNumbProperList()));
        }

        showList();
    }

    public void showList() {
        tableOfResidentsTB.setModel(new TableModels.ZoznamObcanovNaNehnutelnostiTabModel(system.findPropertyByRegNumb(Integer.parseInt(regNumbTF.getText())).getListOfResidents()));
        if(!propertyListTF.getText().isEmpty()){
        tableOwnersTB.setModel(new TableModels.ZoznamPodielovNaListeVlastnictva(system.findPropertyListByNumber(Integer.parseInt(propertyListTF.getText())).getOwnership().getPersons(), system.findPropertyListByNumber(Integer.parseInt(propertyListTF.getText())).getOwnership().getPersonParts()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        regNumbTF = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        adressTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        descriptionTF = new javax.swing.JTextField();
        saveBT = new javax.swing.JButton();
        editBT = new javax.swing.JButton();
        adddBT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOfResidentsTB = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOwnersTB = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ownerIDTF = new javax.swing.JTextField();
        addCitizienTF = new javax.swing.JTextField();
        addCitizienBT = new javax.swing.JButton();
        addOwnerBT = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        partTF = new javax.swing.JTextField();
        changeOwnerBT = new javax.swing.JButton();
        newOwnersIDTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        findBT = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        propertyListTF = new javax.swing.JTextField();
        numbOfCatAreaTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        showPropertyListBT = new javax.swing.JButton();
        ShowCadAreaBT = new javax.swing.JButton();

        jLabel1.setText("Súpisné číslo:");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setLabelFor(jLabel1);
        jLabel2.setText("Nehnuteľnosť");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setText("Adresa:");
        jLabel3.setToolTipText("");

        jLabel4.setText("Popis:");

        saveBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        saveBT.setText("Ulož nehnuteľnosť");
        saveBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTActionPerformed(evt);
            }
        });

        editBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        editBT.setText("Uprav nehnuteľnosť");
        editBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTActionPerformed(evt);
            }
        });

        adddBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.png"))); // NOI18N
        adddBT.setText("Pridaj nehnuteľnosť");
        adddBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddBTActionPerformed(evt);
            }
        });

        tableOfResidentsTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableOfResidentsTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOfResidentsTBMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableOfResidentsTB);

        tableOwnersTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableOwnersTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOwnersTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableOwnersTB);

        jLabel5.setText("Zoznam obyvateľov nehnuteľnosti");

        jLabel6.setText("Zoznam vlastníkov nehnuteľnosti");

        jLabel7.setText("Rodné číslo majiteľa:");

        ownerIDTF.setEnabled(false);

        addCitizienTF.setEnabled(false);

        addCitizienBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addCitizienBT.setText("Pridaj obyvateľa");
        addCitizienBT.setEnabled(false);
        addCitizienBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCitizienBTActionPerformed(evt);
            }
        });

        addOwnerBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addOwnerBT.setText("Pridaj majiteľa");
        addOwnerBT.setEnabled(false);
        addOwnerBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOwnerBTActionPerformed(evt);
            }
        });

        jLabel8.setText("Rodné číslo obyvateľa:");

        jLabel11.setText("Vlastnícky podiel:");

        partTF.setEnabled(false);

        changeOwnerBT.setText("Zmena majiteľa");
        changeOwnerBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeOwnerBTActionPerformed(evt);
            }
        });

        jLabel12.setText("Rodné číslo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCitizienTF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCitizienBT, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newOwnersIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(changeOwnerBT))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ownerIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(partTF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addOwnerBT))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(changeOwnerBT)
                        .addComponent(newOwnersIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCitizienTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCitizienBT)
                    .addComponent(jLabel7)
                    .addComponent(ownerIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addOwnerBT)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(partTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        findBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kripto-search-b.png"))); // NOI18N
        findBT.setText("Vyhľadaj inú nehnuteľnosť");
        findBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBTActionPerformed(evt);
            }
        });

        jLabel9.setText("List vlastníctva:");

        propertyListTF.setEnabled(false);

        numbOfCatAreaTF.setEnabled(false);

        jLabel10.setText("Číslo kat. územia:");

        showPropertyListBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/show.png"))); // NOI18N
        showPropertyListBT.setText("Zobraz");
        showPropertyListBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPropertyListBTActionPerformed(evt);
            }
        });

        ShowCadAreaBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/show.png"))); // NOI18N
        ShowCadAreaBT.setText("Zobraz");
        ShowCadAreaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowCadAreaBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adressTF)
                                    .addComponent(descriptionTF)
                                    .addComponent(regNumbTF)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(numbOfCatAreaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(propertyListTF))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ShowCadAreaBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(showPropertyListBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(findBT)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(adddBT)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(editBT)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saveBT)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regNumbTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(adressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(descriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saveBT)
                        .addComponent(editBT)
                        .addComponent(adddBT)
                        .addComponent(findBT))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(propertyListTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(showPropertyListBT)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numbOfCatAreaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ShowCadAreaBT))
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adddBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddBTActionPerformed
        if (regNumbTF.getText().isEmpty() || adressTF.getText().isEmpty() || descriptionTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(mainWindow, "Vyplňte súpisné číslo, adresu a popis k nehnuteľnosti");
            return;
        } else {
            system.addProperty(Integer.parseInt(regNumbTF.getText()), adressTF.getText(), descriptionTF.getText());
            regNumbTF.setText("");
            adressTF.setText("");
            descriptionTF.setText("");
        }

    }//GEN-LAST:event_adddBTActionPerformed

    private void editBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTActionPerformed
        regNumbTF.setEditable(true);
        adressTF.setEditable(true);
        descriptionTF.setEditable(true);

        saveBT.setEnabled(true);

    }//GEN-LAST:event_editBTActionPerformed

    private void saveBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTActionPerformed
        if (regNumbTF.getText().isEmpty() || adressTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(mainWindow, "Súpisné číslo a adresa musia byť vyplnené.");
            return;
        } else {
            ((Property) system.getProperties().findNode(propertyBeforeChanges).getData()).setRegNumber(Integer.parseInt(regNumbTF.getText()));
            ((Property) system.getProperties().findNode(propertyBeforeChanges).getData()).setAdress(adressTF.getText());
            ((Property) system.getProperties().findNode(propertyBeforeChanges).getData()).setDescription(descriptionTF.getText());
        }

    }//GEN-LAST:event_saveBTActionPerformed

    private void tableOfResidentsTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOfResidentsTBMouseClicked
        if (evt.getClickCount() == 2) {

            int selectedRowIndex = tableOfResidentsTB.getSelectedRow();

            String firstName = tableOfResidentsTB.getValueAt(selectedRowIndex, 0).toString();
            String surName = tableOfResidentsTB.getValueAt(selectedRowIndex, 1).toString();
            String identifNum = tableOfResidentsTB.getValueAt(selectedRowIndex, 2).toString();

            Person person = new Person(firstName, surName, Long.parseLong(identifNum), system.findPropertyByRegNumb(Integer.parseInt(regNumbTF.getText())));
            Obcan panel = new Obcan(mainWindow, system, (Person) system.getCitiziens().findNode(person).getData());
            Globals.panel.addTab("Občan " + surName, panel);
            logika.setLastTab();
    }//GEN-LAST:event_tableOfResidentsTBMouseClicked
    }
    private void addOwnerBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOwnerBTActionPerformed
        if (system.findPersonByID(Long.parseLong(ownerIDTF.getText())) != null) {
            //system.findPropertyByRegNumb(regNumbTF.getText()).addOwnerOfProperty(system.findPersonByID(ownerIDTF.getText()));
            // system.findPropertyByRegNumb(regNumbTF.getText()).getOwnership().addPerson(system.findPersonByID(ownerIDTF.getText()), Double.parseDouble(partTF.getText()));
        } else {
            JOptionPane.showMessageDialog(mainWindow, "Osoba s daným rodným číslom neexistuje.");
            ownerIDTF.setText("");
            return;
        }
        showList();
    }//GEN-LAST:event_addOwnerBTActionPerformed

    private void tableOwnersTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOwnersTBMouseClicked
        if (evt.getClickCount() == 2) {

            int selectedRowIndex = tableOwnersTB.getSelectedRow();

            String firstName = tableOwnersTB.getValueAt(selectedRowIndex, 0).toString();
            String surName = tableOwnersTB.getValueAt(selectedRowIndex, 1).toString();
            String identifNum = tableOwnersTB.getValueAt(selectedRowIndex, 2).toString();

            Person person = new Person(firstName, surName, Long.parseLong(identifNum), system.findPropertyByRegNumb(Integer.parseInt(regNumbTF.getText())));
            Obcan panel = new Obcan(mainWindow, system, (Person) system.getCitiziens().findNode(person).getData());
            Globals.panel.addTab("Občan " + surName, panel);
            logika.setLastTab();
        }
    }//GEN-LAST:event_tableOwnersTBMouseClicked

    private void findBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBTActionPerformed

    }//GEN-LAST:event_findBTActionPerformed

    private void showPropertyListBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPropertyListBTActionPerformed
        PropertyList list = system.findPropertyListByNumber(Integer.parseInt(propertyListTF.getText()));
        ListVlastnictva panel = new ListVlastnictva(mainWindow, system, list);
        Globals.panel.addTab("List vlastníctva " + propertyListTF.getText(), panel);
        logika.setLastTab();
    }//GEN-LAST:event_showPropertyListBTActionPerformed

    private void ShowCadAreaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowCadAreaBTActionPerformed
        CadastralArea area = system.findCadAreaByNumber(Integer.parseInt(numbOfCatAreaTF.getText()));
        KatastralneUzemie panel = new KatastralneUzemie(mainWindow, system, area);
        Globals.panel.addTab("Katastrálne územie " + numbOfCatAreaTF.getText(), panel);
        logika.setLastTab();
    }//GEN-LAST:event_ShowCadAreaBTActionPerformed

    private void addCitizienBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCitizienBTActionPerformed
        if (system.findPersonByID(Long.parseLong(addCitizienTF.getText())).getPermResidence() != null) {
            JOptionPane.showMessageDialog(mainWindow, "Osoba s daným rodným číslom už má trvalý pobyt v inej henuteľnosti");
            return;
        } else {
            system.findPropertyByRegNumb(Integer.parseInt(regNumbTF.getText())).addResident(system.findPersonByID(Long.parseLong(addCitizienTF.getText())));
            system.findPersonByID(Long.parseLong(addCitizienTF.getText())).setPermResidence(system.findPropertyByRegNumb(Integer.parseInt(regNumbTF.getText())));
            showList();
        }
    }//GEN-LAST:event_addCitizienBTActionPerformed

    private void changeOwnerBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeOwnerBTActionPerformed
        int row = tableOwnersTB.getSelectedRow();
        double oldOnwership = 0.0;
        int indexOfDelete = -5;
        if (row >= 0) {
            String deleteID = tableOwnersTB.getModel().getValueAt(row, 2).toString();
            ArrayList<String> list = system.findPropertyListByNumber(Integer.parseInt(propertyListTF.getText())).getOwnership().getPersonParts();
            for (int i = 0; i < list.size(); i++) {
                String[] values = list.get(i).split(";");
                if (values[0].compareTo(deleteID) == 0) {
                    indexOfDelete = i;
                    oldOnwership = Double.parseDouble(values[1]);
                }
            }
            ///dorobit
            if (system.findPropertyListByNumber(Integer.parseInt(propertyListTF.getText())).getOwnership().getPersons().insert(system.findPersonByID(Long.parseLong(newOwnersIDTF.getText())))) {

                system.findPropertyListByNumber(Integer.parseInt(propertyListTF.getText())).getOwnership().getPersonParts().add(system.findPersonByID(Long.parseLong(newOwnersIDTF.getText())).getIdentifNumb() + ";" + Double.toString(oldOnwership));
                if (indexOfDelete >= 0) {
                    system.findPropertyListByNumber(Integer.parseInt(propertyListTF.getText())).getOwnership().getPersons().delete(system.findPersonByID(Long.parseLong(deleteID)));
                    system.findPropertyListByNumber(Integer.parseInt(propertyListTF.getText())).getOwnership().getPersonParts().remove(indexOfDelete);
                    showList();
                }
            } else {
                JOptionPane.showMessageDialog(mainWindow, "Nový majiteľ s daným rodným číslom neexistuje");
            }

        } else {
            JOptionPane.showMessageDialog(mainWindow, "Vyberte majiteľa, ktorého chcete zmeniť.");
        }

    }//GEN-LAST:event_changeOwnerBTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ShowCadAreaBT;
    private javax.swing.JButton addCitizienBT;
    private javax.swing.JTextField addCitizienTF;
    private javax.swing.JButton addOwnerBT;
    private javax.swing.JButton adddBT;
    private javax.swing.JTextField adressTF;
    private javax.swing.JButton changeOwnerBT;
    private javax.swing.JTextField descriptionTF;
    private javax.swing.JButton editBT;
    private javax.swing.JButton findBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField newOwnersIDTF;
    private javax.swing.JTextField numbOfCatAreaTF;
    private javax.swing.JTextField ownerIDTF;
    private javax.swing.JTextField partTF;
    private javax.swing.JTextField propertyListTF;
    private javax.swing.JTextField regNumbTF;
    private javax.swing.JButton saveBT;
    private javax.swing.JButton showPropertyListBT;
    private javax.swing.JTable tableOfResidentsTB;
    private javax.swing.JTable tableOwnersTB;
    // End of variables declaration//GEN-END:variables
}
