/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FiltersAndOthers;

import AVL.AVLTree;
import GUI.ListVlastnictva;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import mainpackage.CadastralArea;
import mainpackage.MainSystem;
import mainpackage.Person;
import mainpackage.Property;
import mainpackage.PropertyList;

/**
 *
 * @author Vladko
 */
public class ChangeCadAreaOnList extends javax.swing.JFrame {

    private MainSystem system;
    private int listID;
    private ListVlastnictva list;

    public ChangeCadAreaOnList(MainSystem system, int listID, ListVlastnictva frame) {
        initComponents();
        this.system = system;
        this.listID = listID;
        list = frame;
        setVisible(true);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
   

    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        regNumbTF = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Zmena katastrálneho územia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Zmena katastrálneho územia");

        jLabel2.setBackground(new java.awt.Color(102, 255, 102));
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Zadajte číslo katastrálneho územia");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closeAll.jpg"))); // NOI18N
        jButton2.setText("Zavri");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Číslo kat. územia:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(44, 44, 44)
                                .addComponent(jButton2))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(regNumbTF))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regNumbTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (regNumbTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Zadajte číslo kat územia");
        } else {
            if(system.findCadArea(Integer.parseInt(regNumbTF.getText())) != null){
            if(system.findPropertyListByNumber(listID).getCadastralArea()!= null){
            system.findCadAreaByNumber(system.findPropertyListByNumber(listID).getCadastralArea().getNumbCadArea()).deletePropertyList(system.findPropertyListByNumber(listID));
            //system.findPropertyListByNumber(listID).setPropertiesOnList(system.findCadAreaByNumber(parts[0]).getPropertiesOnCadArea());
            ArrayList<Comparable<Property>> list = new ArrayList();
            system.findPropertyListByNumber(listID).getPropertiesOnList().inOrderTraverseTreeArray(system.findPropertyListByNumber(listID).getPropertiesOnList().getRoot(), list);
            for(int i = 0; i < list.size();i++){
                system.findProperty((Property)list.get(i)).setCadArea(system.findCadAreaByNumber(Integer.parseInt(regNumbTF.getText())));
            }     
            }
            system.findPropertyListByNumber(listID).setCadastralArea(system.findCadAreaByNumber(Integer.parseInt(regNumbTF.getText())));
            system.findCadAreaByNumber(Integer.parseInt(regNumbTF.getText())).addPropertyList(system.findPropertyListByNumber(listID));
            }else{
               JOptionPane.showMessageDialog(this, "Zadané katatstrálne územie územie neexistuje."); 
            }
        }
        list.showList();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeCadAreaOnList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeCadAreaOnList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeCadAreaOnList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeCadAreaOnList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeCadAreaOnList(null, 0,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField regNumbTF;
    // End of variables declaration//GEN-END:variables
}
