/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FiltersAndOthers;

import GUI.Nehnutelnost;
import javax.swing.JOptionPane;
import mainpackage.Globals;
import mainpackage.Logika;
import mainpackage.MainSystem;

/**
 *
 * @author Vladko
 */
public class FilterZoznamNehnutelnosti extends javax.swing.JFrame {

    MainSystem system;
    Logika logika = new Logika();

    public FilterZoznamNehnutelnosti(MainSystem system) {
        setSize(400, 400);
        setLocation(600, 300);
        setVisible(true);
        initComponents();
        this.system = system;
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        regNumbTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numberOfCadAreaTF = new javax.swing.JTextField();
        searchBT = new javax.swing.JButton();
        closeBT = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        numberPropertyListTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Súpisné číslo:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Vyhľadaj nehnuteľnosť");

        jLabel3.setText("Č.Kat územia:");

        searchBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kripto-search-b.png"))); // NOI18N
        searchBT.setText("Vyhľadaj");
        searchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTActionPerformed(evt);
            }
        });

        closeBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closeAll.jpg"))); // NOI18N
        closeBT.setText("Zavri");
        closeBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBTActionPerformed(evt);
            }
        });

        jLabel4.setText("Číslo listu v:");

        numberPropertyListTF.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchBT)
                        .addGap(67, 67, 67)
                        .addComponent(closeBT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel2)
                        .addGap(0, 114, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberPropertyListTF)
                            .addComponent(regNumbTF)
                            .addComponent(numberOfCadAreaTF))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(regNumbTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numberOfCadAreaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numberPropertyListTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeBT)
                    .addComponent(searchBT))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTActionPerformed
        if (regNumbTF.getText() != "" && numberOfCadAreaTF.getText() != null) {
            if (!numberPropertyListTF.getText().isEmpty()) {
                 if (system.findPropertyByRegNumb(Integer.parseInt(regNumbTF.getText())) != null && system.findCadArea(Integer.parseInt(numberOfCadAreaTF.getText())) != null
                        && system.findPropertyByRegNumb(Integer.parseInt(regNumbTF.getText())).getCadArea().getNumbCadArea() == Integer.parseInt(numberOfCadAreaTF.getText()) 
                         && system.findPropertyByRegNumb(Integer.parseInt(regNumbTF.getText())).getPropertyList().getNumbProperList() == (Integer.parseInt(numberPropertyListTF.getText()))) {
                    Nehnutelnost panel = new Nehnutelnost(this, system, system.findPropertyByRegNumb(Integer.parseInt(regNumbTF.getText())));
                    Globals.panel.addTab("Nehnuteľnosť " + regNumbTF.getText(), panel);
                    logika.setLastTab();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(Globals.panel, "Nie je možné nájsť nehnuteľnosť s týmito hodnotami.");
                }
            } else {
                if (system.findPropertyByRegNumb(Integer.parseInt(regNumbTF.getText())) != null && system.findCadArea(Integer.parseInt(numberOfCadAreaTF.getText())) != null
                    && system.findPropertyByRegNumb(Integer.parseInt(regNumbTF.getText())).getCadArea() != null && system.findPropertyByRegNumb(Integer.parseInt(regNumbTF.getText())).getCadArea().getNumbCadArea() == Integer.parseInt(numberOfCadAreaTF.getText())) {
                    Nehnutelnost panel = new Nehnutelnost(this, system, system.findPropertyByRegNumb(Integer.parseInt(regNumbTF.getText())));
                    Globals.panel.addTab("Nehnuteľnosť " + regNumbTF.getText(), panel);
                    logika.setLastTab();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(Globals.panel, "Nie je možné nájsť nehnuteľnosť s týmito hodnotami.");
                }
            }
        }else{
            JOptionPane.showMessageDialog(Globals.panel, "Musí byť zadané súpisné číslo a číslo kat. územia.");
        }
        
    }//GEN-LAST:event_searchBTActionPerformed

    private void closeBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBTActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilterZoznamNehnutelnosti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilterZoznamNehnutelnosti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilterZoznamNehnutelnosti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilterZoznamNehnutelnosti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilterZoznamNehnutelnosti(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField numberOfCadAreaTF;
    private javax.swing.JTextField numberPropertyListTF;
    private javax.swing.JTextField regNumbTF;
    private javax.swing.JButton searchBT;
    // End of variables declaration//GEN-END:variables
}
